import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core';

export const instruments = sqliteTable('instruments', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  instrumentToken: integer('instrument_token').notNull().unique(),
  exchangeToken: integer('exchange_token'),
  tradingsymbol: text('tradingsymbol').notNull(),
  name: text('name'),
  exchange: text('exchange').notNull(),
  segment: text('segment'),
  instrumentType: text('instrument_type'),
  lotSize: integer('lot_size').default(1),
  tickSize: real('tick_size').default(0.05),
  isNifty500: integer('is_nifty500', { mode: 'boolean' }).default(false),
  sector: text('sector'),
  marketCap: real('market_cap'),
  isASM: integer('is_asm', { mode: 'boolean' }).default(false),
  isGSM: integer('is_gsm', { mode: 'boolean' }).default(false),
  updatedAt: text('updated_at').notNull(),
}, (table) => [
  index('idx_instruments_tradingsymbol').on(table.tradingsymbol),
  index('idx_instruments_exchange').on(table.exchange),
]);

export const marketData = sqliteTable('market_data', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  instrumentToken: integer('instrument_token').notNull(),
  tradingsymbol: text('tradingsymbol').notNull(),
  timestamp: text('timestamp').notNull(),
  open: real('open').notNull(),
  high: real('high').notNull(),
  low: real('low').notNull(),
  close: real('close').notNull(),
  volume: integer('volume').notNull(),
  oi: integer('oi'),
  interval: text('interval').notNull(),
}, (table) => [
  index('idx_market_data_symbol_time').on(table.tradingsymbol, table.timestamp),
  index('idx_market_data_token_interval').on(table.instrumentToken, table.interval, table.timestamp),
]);

export const indicatorSnapshots = sqliteTable('indicator_snapshots', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tradingsymbol: text('tradingsymbol').notNull(),
  date: text('date').notNull(),
  ema20: real('ema20'),
  ema50: real('ema50'),
  ema200: real('ema200'),
  rsi14: real('rsi14'),
  adx14: real('adx14'),
  atr14: real('atr14'),
  weeklyReturn: real('weekly_return'),
  volumeRatio: real('volume_ratio'),
  patterns: text('patterns'),
  createdAt: text('created_at').notNull(),
}, (table) => [
  index('idx_indicator_symbol_date').on(table.tradingsymbol, table.date),
]);

export const tradingSignals = sqliteTable('trading_signals', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  date: text('date').notNull(),
  tradingsymbol: text('tradingsymbol').notNull(),
  exchange: text('exchange').notNull(),
  cmp: real('cmp').notNull(),
  action: text('action').notNull(),
  entry: real('entry'),
  stopLoss: real('stop_loss'),
  target: real('target'),
  positionSize: integer('position_size'),
  riskRewardRatio: real('risk_reward_ratio'),
  confidence: real('confidence'),
  reasoning: text('reasoning'),
  phase: text('phase').notNull(),
  metadata: text('metadata'),
  createdAt: text('created_at').notNull(),
});

export const orders = sqliteTable('orders', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  orderId: text('order_id'),
  tradingsymbol: text('tradingsymbol').notNull(),
  exchange: text('exchange').notNull(),
  transactionType: text('transaction_type').notNull(),
  orderType: text('order_type').notNull(),
  product: text('product').notNull(),
  quantity: integer('quantity').notNull(),
  price: real('price'),
  triggerPrice: real('trigger_price'),
  status: text('status').notNull(),
  mode: text('mode').notNull(),
  tag: text('tag'),
  parentSignalId: integer('parent_signal_id'),
  filledQuantity: integer('filled_quantity'),
  averagePrice: real('average_price'),
  statusMessage: text('status_message'),
  placedAt: text('placed_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const positions = sqliteTable('positions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tradingsymbol: text('tradingsymbol').notNull(),
  exchange: text('exchange').notNull(),
  quantity: integer('quantity').notNull(),
  averageEntry: real('average_entry').notNull(),
  currentPrice: real('current_price'),
  stopLoss: real('stop_loss').notNull(),
  target: real('target').notNull(),
  trailingStopActive: integer('trailing_stop_active', { mode: 'boolean' }).default(false),
  trailingStopPrice: real('trailing_stop_price'),
  pnl: real('pnl'),
  pnlPercent: real('pnl_percent'),
  mode: text('mode').notNull(),
  entryOrderId: integer('entry_order_id'),
  status: text('status').notNull(),
  enteredAt: text('entered_at').notNull(),
  closedAt: text('closed_at'),
});

export const portfolioSnapshots = sqliteTable('portfolio_snapshots', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  date: text('date').notNull().unique(),
  totalEquity: real('total_equity').notNull(),
  dailyPnl: real('daily_pnl').notNull(),
  dailyPnlPercent: real('daily_pnl_percent').notNull(),
  openPositions: integer('open_positions').notNull(),
  peakEquity: real('peak_equity').notNull(),
  drawdown: real('drawdown').notNull(),
  drawdownPercent: real('drawdown_percent').notNull(),
  mode: text('mode').notNull(),
});

export const backtestRuns = sqliteTable('backtest_runs', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  startDate: text('start_date').notNull(),
  endDate: text('end_date').notNull(),
  initialCapital: real('initial_capital').notNull(),
  finalEquity: real('final_equity'),
  cagr: real('cagr'),
  sharpeRatio: real('sharpe_ratio'),
  maxDrawdown: real('max_drawdown'),
  winRate: real('win_rate'),
  totalTrades: integer('total_trades'),
  config: text('config'),
  results: text('results'),
  createdAt: text('created_at').notNull(),
});
