export function Footer() {
  return (
    <footer className="py-12 px-6 border-t border-border bg-card/30">
      <div className="max-w-7xl mx-auto text-center">
        <p className="text-sm text-muted-foreground">
          Generated by <span className="font-semibold">Superagent</span>
        </p>
      </div>
    </footer>
  )
}
